version: 2.1
orbs:
  docker: circleci/docker@1.4.0

commands:
  login_github_container_registory:
    parameters:
      user:
        type: string
      password:
        type: env_var_name
        default: CR_PAT
    steps:
      - run:
          name: auth ghcr
          command: |
            echo ${<< parameters.password >>} | docker login ghcr.io -u << parameters.user >> --password-stdin

jobs:
  check_dockerhub:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - docker/check
  
  check_ghcr:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - login_github_container_registory:
          user: taguchi8s

release-filters: &release-filters
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

workflows:
  test:
    jobs:
      - check_dockerhub
      - check_ghcr
      - docker/hadolint:
          dockerfiles: src/Dockerfile
          workspace-root: src
      - docker/publish:
          image: taguchi8s/cliboa-docker
          tag: latest
          path: src
          docker-context: src
          deploy: false

  deploy-release:
    jobs:
      - check_dockerhub
      - check_ghcr
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: release-${CIRCLE_TAG}
          path: src
          docker-context: src
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: latest
          path: src
          docker-context: src
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: release-${CIRCLE_TAG}
          path: src
          docker-context: src
          registry: ghcr.io
          after_build:
            - login_github_container_registory:
                user: taguchi8s
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: latest
          path: src
          docker-context: src
          registry: ghcr.io
          after_build:
            - login_github_container_registory:
                user: taguchi8s