version: 2.1
orbs:
  docker: circleci/docker@1.4.0

jobs:
  check_dockerhub:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - docker/check
  
  check_ghcr:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - docker/check:
          docker-password: CR_PAT
          docker-username: CR_USER
          registry: ghcr.io

  check_ghpkg:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - docker/check:
          docker-password: CR_PAT
          docker-username: CR_USER
          registry: docker.pkg.github.com

release-filters: &release-filters
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

workflows:
  test:
    jobs:
      - check_dockerhub
      - check_ghcr
      - check_ghpkg
      - docker/hadolint:
          dockerfiles: src/Dockerfile
          workspace-root: src
      - docker/publish:
          image: taguchi8s/cliboa-docker
          tag: latest
          path: src
          docker-context: src
          deploy: false

  deploy-release:
    jobs:
      - check_dockerhub:
          <<: *release-filters
      - check_ghcr:
          <<: *release-filters
      - check_ghpkg:
          <<: *release-filters
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: release-${CIRCLE_TAG}
          path: src
          docker-context: src
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: latest
          path: src
          docker-context: src
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: release-${CIRCLE_TAG}
          path: src
          docker-context: src
          docker-password: CR_PAT
          docker-username: CR_USER
          registry: ghcr.io
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: latest
          path: src
          docker-context: src
          docker-password: CR_PAT
          docker-username: CR_USER
          registry: ghcr.io
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker/cliboa-docker
          tag: release-${CIRCLE_TAG}
          path: src
          docker-context: src
          docker-password: CR_PAT
          docker-username: CR_USER
          registry: docker.pkg.github.com
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker/cliboa-docker
          tag: latest
          path: src
          docker-context: src
          docker-password: CR_PAT
          docker-username: CR_USER
          registry: docker.pkg.github.com