version: 2.1
orbs:
  docker: circleci/docker@1.4.0

commands:
  ghcr_check:
    parameters:
      user:
        type: string
      password:
        type: env_var_name
        default: CR_PAT
    steps:
      - run:
          name: auth ghcr
          command: |
            echo ${<< parameters.password >>} | docker login ghcr.io -u << parameters.user >> --password-stdin
  build:
    parameters:
      image:
        type: string
      tag:
        type: string
      path:
        type: string
    steps:
      - run:
          name: build docker image
          command: |
            cd << parameters.path >>
            docker build -t ghcr.io/<< parameters.image >>:<< parameters.tag >> .
  ghcr_publish:
    parameters:
      image:
        type: string
      tag:
        type: string
      path:
        type: string
    steps:
      - run:
          name: build and publish ghcr
          command: |
            cd << parameters.path >>
            docker build -t ghcr.io/<< parameters.image >>:<< parameters.tag >> .
            docker push ghcr.io/<< parameters.image >>:<< parameters.tag >>

jobs:
  check_dockerhub:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
  
  check_ghcr:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - ghcr_check:
          user: taguchi8s
  
  build:
    parameters:
      image:
        type: string
      tag:
        type: string
      path:
        type: string
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - build:
          image: << parameters.image >>
          tag: << parameters.tag >>
          path: << parameters.path >>

  ghcr_publish:
    parameters:
      image:
        type: string
      tag:
        type: string
      path:
        type: string
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - ghcr_check:
          user: taguchi8s
      - ghcr_publish:
          image: << parameters.image >>
          tag: << parameters.tag >>
          path: << parameters.path >>

release-filters: &release-filters
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

workflows:
  deploy-latest:
    jobs:
      - check_dockerhub
      - check_ghcr
      - docker/hadolint:
          dockerfiles: src/Dockerfile
          workspace-root: src
      - build:
          image: taguchi8s/cliboa-docker
          tag: latest
          path: src
          requires:
            - docker/hadolint
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: latest
          path: src
          requires:
            - check_dockerhub
            - build
      - ghcr_publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: latest
          path: src
          requires:
            - check_ghcr
            - build

  deploy-release:
    jobs:
      - check_dockerhub
      - check_ghcr
      - docker/hadolint:
          dockerfiles: src/Dockerfile
          workspace-root: src
      - build:
          image: taguchi8s/cliboa-docker
          tag: latest
          path: src
          requires:
            - docker/hadolint
      - docker/publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: release-${CIRCLE_TAG}
          path: src
          requires:
            - check_dockerhub
            - build
      - ghcr_publish:
          <<: *release-filters
          image: taguchi8s/cliboa-docker
          tag: release-${CIRCLE_TAG}
          path: src
          requires:
            - check_ghcr
            - build